### PR TITLE
Fix pre-compile on cpu-only machines

### PR DESCRIPTION
**Pull request by AlongWY**
+ Fix pre-compile on cpu-only machines

### CODE REVIEW

File: accelerator/cuda_accelerator.py [hunk 1]
```diff
@@ -242,6 +242,8 @@ def communication_backend_name(self):
         return self._communication_backend_name
 
     def is_triton_supported(self):
+        if not torch.cuda.is_available():
```
Comment (tjruwase) [inline accelerator/cuda_accelerator.py:245]:
```suggestion
        if not self.is_available():
```

Comment (tjruwase) [reply accelerator/cuda_accelerator.py:245]: Please change as above

**Comment by tjruwase** [comment]
@AlongWY, thanks for the PR. Can you please share the motivation to help us understand your use case?

**Comment by AlongWY** [comment]
> @AlongWY, thanks for the PR. Can you please share the motivation to help us understand your use case?

I used GitHub Actions to precompile DeepSpeed, but after upgrading to v0.16.4, the precompilation failed. The repository is here: https://github.com/AlongWY/deepspeed_wheels

**Comment by loadams** [comment]
> > @AlongWY, thanks for the PR. Can you please share the motivation to help us understand your use case?
> 
> I used GitHub Actions to precompile DeepSpeed, but after upgrading to v0.16.4, the precompilation failed. The repository is here: https://github.com/AlongWY/deepspeed_wheels
> 
> And the [compile result](https://github.com/AlongWY/deepspeed_wheels/actions/runs/14005965046/job/39219890195#step:10:5216) here show that tranformer inference is not support cuda 12.6, which is also shown in #6709.

@AlongWY - just so I follow, you're compiling on Windows in a GitHub action that has cuda installed but no GPU (so that's why you are hitting the CPU only path here) but with DS_ACCELERATOR=cuda?  Just wanted to make sure I understood the repo correctly?

**Comment by AlongWY** [comment]
Yes, the GitHub Action is compiling in an Ubuntu environment with CUDA installed but without a GPU.  
The GitHub Action runs only on Ubuntu, but the error still occurs.

**Comment by AlongWY** [comment]
Yes, the triton has been installed in the environment.

# Error for triton
image

# Error for type
image

**Comment by AlongWY** [comment]
Any update?

**Comment by sfc-gh-truwase** [comment]
> Any update?

@AlongWY apologies for the delay. This overall looks good to me. I will appreciate a couple more clarifications. 
1. I am curious why [accelerator detection logic](https://github.com/deepspeedai/DeepSpeed/blob/cda3f9628cfe1dd90c7af10ddc5b8d3b16aa459c/accelerator/real_accelerator.py#L51) is incorrectly [identifying as cuda env.](https://github.com/deepspeedai/DeepSpeed/blob/cda3f9628cfe1dd90c7af10ddc5b8d3b16aa459c/accelerator/real_accelerator.py#L201). Or are you hardcoding DS_ACCELERATOR=cuda` in your code?
2. Are you aligned with the suggested code change?

**Comment by AlongWY** [comment]
@sfc-gh-truwase Hi, i have update the code.

For the two questions:
1. I use GitHub Actions to automatically build wheel packages for different environments, so I manually set the environment variable DS_ACCELERATOR=cuda.  
2. I have aligned with the suggested code change.
